/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biologygameapp;

/**
 *
 * @author Lee
 */
public class BioPhotosyn extends javax.swing.JFrame {

    /**
     * Creates new form BioPhotosyn
     */
    public BioPhotosyn() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BioHistoryBackground = new javax.swing.JLabel();
        BackButton = new javax.swing.JLabel();
        HomeButton = new javax.swing.JLabel();
        HelpButton = new javax.swing.JLabel();
        BioPhotosynImg = new javax.swing.JLabel();
        PhotosynTitle = new javax.swing.JLabel();
        BioHistoryBackground1 = new javax.swing.JLabel();

        BioHistoryBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/BiologyBackground.jpg"))); // NOI18N
        BioHistoryBackground.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/backbtn.png"))); // NOI18N
        BackButton.setText("jLabel1");
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        getContentPane().add(BackButton);
        BackButton.setBounds(0, 350, 130, 50);

        HomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/homebtn.png"))); // NOI18N
        HomeButton.setText("jLabel1");
        HomeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeButtonMouseClicked(evt);
            }
        });
        getContentPane().add(HomeButton);
        HomeButton.setBounds(130, 350, 60, 50);

        HelpButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/helpbtn.png"))); // NOI18N
        HelpButton.setText("jLabel1");
        getContentPane().add(HelpButton);
        HelpButton.setBounds(180, 350, 140, 50);

        BioPhotosynImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/Photosynthesis.png"))); // NOI18N
        BioPhotosynImg.setText("jLabel1");
        getContentPane().add(BioPhotosynImg);
        BioPhotosynImg.setBounds(-30, 80, 330, 260);

        PhotosynTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        PhotosynTitle.setForeground(new java.awt.Color(0, 204, 102));
        PhotosynTitle.setText("Photosynthesis");
        getContentPane().add(PhotosynTitle);
        PhotosynTitle.setBounds(80, 10, 140, 30);

        BioHistoryBackground1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/biologygameapp/BiologyBackground.jpg"))); // NOI18N
        BioHistoryBackground1.setText("jLabel2");
        getContentPane().add(BioHistoryBackground1);
        BioHistoryBackground1.setBounds(0, 0, 320, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BackButtonMouseClicked

    private void HomeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HomeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BioPhotosyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BioPhotosyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BioPhotosyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BioPhotosyn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BioPhotosyn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackButton;
    private javax.swing.JLabel BioHistoryBackground;
    private javax.swing.JLabel BioHistoryBackground1;
    private javax.swing.JLabel BioPhotosynImg;
    private javax.swing.JLabel HelpButton;
    private javax.swing.JLabel HomeButton;
    private javax.swing.JLabel PhotosynTitle;
    // End of variables declaration//GEN-END:variables
}
